export const countries = {
  Afghanistan: "Asia",
  Albania: "Europe",
  Algeria: "Africa",
  "American Samoa": "Oceania",
  Andorra: "Europe",
  Angola: "Africa",
  Anguilla: "North America",
  "Antigua and Barbuda": "North America",
  Argentina: "South America",
  Armenia: "Asia",
  Aruba: "North America",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "Asia",
  Bahamas: "North America",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Barbados: "North America",
  Belarus: "Europe",
  Belgium: "Europe",
  Belize: "South America",
  Benin: "Africa",
  Bermuda: "North America",
  Bhutan: "Asia",
  "Bolivia (Plurinational State of)": "South America",
  "Bosnia and Herzegovina": "Europe",
  Botswana: "Africa",
  Brazil: "South America",
  "Brunei Darussalam": "Asia",
  Bulgaria: "Europe",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  "Cabo Verde": "Africa",
  Cambodia: "Asia",
  Cameroon: "Africa",
  Canada: "North America",
  "Cayman Islands": "North America",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Chile: "South America",
  China: "Asia",
  "Christmas Island": "Asia",
  Colombia: "South America",
  Comoros: "Africa",
  "Congo (the Democratic Republic of the)": "Africa",
  Congo: "Africa",
  "Cook Islands": "Oceania",
  "Costa Rica": "North America",
  Croatia: "Europe",
  Cuba: "North America",
  Curaçao: "North America",
  Cyprus: "Europe",
  Czechia: "Europe",
  "Côte d'Ivoire": "Africa",
  Denmark: "Europe",
  Djibouti: "Africa",
  Dominica: "North America",
  "Dominican Republic": "North America",
  Ecuador: "South America",
  Egypt: "Africa",
  "El Salvador": "North America",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Estonia: "Europe",
  Eswatini: "Africa",
  Ethiopia: "Africa",
  "Falkland Islands [Malvinas]": "Europe",
  "Faroe Islands": "Europe",
  Fiji: "Oceania",
  Finland: "Europe",
  France: "Europe",
  "French Guiana": "South America",
  "French Polynesia": "Oceania",
  Gabon: "Africa",
  Gambia: "Africa",
  Georgia: "Asia",
  Germany: "Europe",
  Ghana: "Africa",
  Gibraltar: "Europe",
  Greece: "Europe",
  Greenland: "North America",
  Grenada: "North America",
  Guadeloupe: "North America",
  Guam: "Oceania",
  Guatemala: "North America",
  Guernsey: "Europe",
  Guinea: "Africa",
  "Guinea-Bissau": "Africa",
  Guyana: "South America",
  Haiti: "North America",
  Honduras: "North America",
  "Hong Kong": "Asia",
  Hungary: "Europe",
  Iceland: "Europe",
  India: "Asia",
  Indonesia: "Asia",
  "Iran (Islamic Republic of)": "Asia",
  Iraq: "Asia",
  Ireland: "Europe",
  "Isle of Man": "Europe",
  Israel: "Asia",
  Italy: "Europe",
  Jamaica: "Europe",
  Japan: "Asia",
  Jersey: "Europe",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kenya: "Africa",
  Kiribati: "Oceania",
  "Korea (the Democratic People's Republic of)": "Asia",
  "Korea (the Republic of)": "Asia",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  "Lao People's Democratic Republic": "Asia",
  Latvia: "Europe",
  Lebanon: "Asia",
  Lesotho: "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Macao: "Asia",
  Madagascar: "Africa",
  Malawi: "Africa",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mali: "Africa",
  Malta: "Europe",
  "Marshall Islands": "South America",
  Martinique: "North America",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Mayotte: "Africa",
  Mexico: "North America",
  "Micronesia (Federated States of)": "Oceania",
  "Moldova (the Republic of)": "Europe",
  Monaco: "Europe",
  Mongolia: "Asia",
  Montenegro: "Europe",
  Montserrat: "North America",
  Morocco: "Africa",
  Mozambique: "Africa",
  Myanmar: "Asia",
  Namibia: "Africa",
  Nauru: "Oceania",
  Nepal: "Asia",
  Netherlands: "Europe",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  Nicaragua: "North America",
  Niger: "Africa",
  Nigeria: "Africa",
  Niue: "Oceania",
  "Norfolk Island": "South America",
  "Northern Mariana Islands": "Oceania",
  Norway: "Europe",
  Oman: "Asia",
  Pakistan: "Asia",
  Palau: "Oceania",
  "Palestine, State of": "Asia",
  Panama: "North America",
  "Papua New Guinea": "Oceania",
  Paraguay: "South America",
  Peru: "South America",
  Philippines: "Asia",
  Pitcairn: "Oceania",
  Poland: "Europe",
  Portugal: "Europe",
  "Puerto Rico": "North America",
  Qatar: "Asia",
  "Republic of North Macedonia": "Europe",
  Romania: "Europe",
  "Russian Federation": "Europe",
  Rwanda: "Africa",
  Réunion: "Africa",
  "Saint Barthélemy": "North America",
  "Saint Helena, Ascension and Tristan da Cunha": "Africa",
  "Saint Kitts and Nevis": "North America",
  "Saint Lucia": "North America",
  "Saint Martin (French part)": "North America",
  "Saint Pierre and Miquelon": "North America",
  "Saint Vincent and the Grenadines": "North America",
  Samoa: "Oceania",
  "San Marino": "Europe",
  "Sao Tome and Principe": "Africa",
  "Saudi Arabia": "Asia",
  Senegal: "Africa",
  Serbia: "Europe",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Singapore: "Asia",
  "Sint Maarten (Dutch part)": "North America",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "Solomon Islands": "Oceania",
  Somalia: "Africa",
  "South Africa": "Africa",
  "South Georgia and the South Sandwich Islands": "South America",
  "South Sudan": "Africa",
  Spain: "Europe",
  "Sri Lanka": "Asia",
  Sudan: "Africa",
  Suriname: "South America",
  "Svalbard and Jan Mayen": "Europe",
  Sweden: "Europe",
  Switzerland: "Europe",
  "Syrian Arab Republic": "Asia",
  Taiwan: "Asia",
  Tajikistan: "Asia",
  "Tanzania, United Republic of": "Africa",
  Thailand: "Asia",
  "Timor-Leste": "Asia",
  Togo: "Africa",
  Tokelau: "Oceania",
  Tonga: "Oceania",
  "Trinidad and Tobago": "North America",
  Tunisia: "Africa",
  Turkey: "Asia",
  Turkmenistan: "Asia",
  "Turks and Caicos Islands": "North America",
  Tuvalu: "Oceania",
  Uganda: "Africa",
  Ukraine: "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States of America": "North America",
  Uruguay: "South America",
  Uzbekistan: "Asia",
  Vanuatu: "Oceania",
  "Venezuela (Bolivarian Republic of)": "South America",
  "Viet Nam": "Asia",
  "Virgin Islands (British)": "North America",
  "Virgin Islands (U.S.)": "North America",
  "Wallis and Futuna": "Oceania",
  "Western Sahara": "Africa",
  Yemen: "Africa",
  Zambia: "Africa",
  Zimbabwe: "Africa",
  "Åland Islands": "Europe",
};
